name: Development workflow

on:
  push:
    branches:
      - NewProcess_DevBranch

env:
  PROJECT_NAME: CICDDeploy
  ORCH_FOLDER: NewProcess
  ORCH_URL: https://cloud.uipath.com/
  ORCH_TENANT: DefaultTenant
  ORCH_ACC_NAME: ABC

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Build UiPath NuGet Package
        shell: pwsh
        run: |
          .\Scripts\UiPathPack.ps1 -project_json .\project.json -destination_folder .\package

      - name: Publish Package to DEV Orchestrator
        shell: pwsh
        env:
          USER_KEY: ${{ secrets.ORCH_USER_KEY_Dev }}
        run: |
          .\Scripts\UiPathDeploy.ps1 -PackagePath .\package -OrchURL ${{ env.ORCH_URL }} -Tenant ${{ env.ORCH_TENANT }} -UserKey $env:USER_KEY
